import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import schema from '../config/settings-schema.json' with { type: 'json' };

await mkdir(new URL('../firmware/main/generated/', import.meta.url), { recursive: true });
await mkdir(new URL('../dist/', import.meta.url), { recursive: true });
let header = '// Generated by npm run build. Do not edit.\n#pragma once\n#include <cstddef>\n#include <cstdint>\nnamespace bitbot::assets {\n';
let total = 0;
for (const [file, symbol] of [['index.html', 'index'], ['style.css', 'style'], ['app.js', 'app']]) {
  const raw = Buffer.from((await readFile(new URL(`../web/${file}`, import.meta.url), 'utf8')).replaceAll('\r\n', '\n'));
  const compressed = gzipSync(raw, { level: 9 });
  // Gzip records the host OS at byte 9. Use "unknown" for identical Windows/Linux builds.
  compressed[9] = 255;
  total += compressed.length;
  header += `inline constexpr uint8_t ${symbol}[] = {\n${[...compressed].map((byte, index) => `${index % 24 ? '' : '\n'}${byte},`).join('')}\n};\n`;
  await writeFile(new URL(`../dist/${file}.gz`, import.meta.url), compressed);
}
header += '}\n';
if (total > 96 * 1024) throw new Error(`Portal exceeds 96 KiB compressed budget: ${total}.`);
await writeFile(new URL('../firmware/main/generated/portal_assets.h', import.meta.url), header);
const defaults = Object.fromEntries(Object.entries(schema.fields).map(([key, rule]) => [key, rule.default]));
await writeFile(new URL('../firmware/main/generated/settings_schema.h', import.meta.url), `// Generated by npm run build. Do not edit.\n#pragma once\nnamespace bitbot {\ninline constexpr const char* kSettingsSchema = R"bitbot(${JSON.stringify(schema.fields)})bitbot";\ninline constexpr const char* kDefaults = R"bitbot(${JSON.stringify(defaults)})bitbot";\n}\n`);
console.log(`Portal: ${total.toLocaleString()} bytes gzip, embedded in firmware. No external assets.`);
